### ISSUE TITLE
NullAudio.driver / Test issues

### ISSUE THREAD

**Issue by ryanfrancesconi** [rnine/AMCoreAudio#52]
It seems there needs to be a new method to base the tests on than the NullAudio.driver. Does that still work for you? I'm unable to see it installed on either of my computers now.

**Comment by rnine** [comment]
No, it doesn't work for me anymore since macOS 11.

My idea was to, somehow, include the `NullAudio.driver` source into the project and build it as part of running tests and/or CI (https://github.com/rnine/SimplyCoreAudio/issues/44.) The source for `NullAudio.driver` can be found [here](  https://developer.apple.com/documentation/coreaudio/creating_an_audio_server_driver_plug-in). Then register it as HAL plugin by following steps similar to what's defined [here](https://github.com/rnine/SimplyCoreAudio/blob/develop/.github/workflows/swift.yml).

**Comment by ryanfrancesconi** [comment]
ok cool, i was looking for the source but couldn't find it. At the moment just want to run the tests to verify a solution for the various API change problems that are also here .....

Haha:
![image](https://user-images.githubusercontent.com/2917795/130818998-690ed144-7b33-4132-bb68-e453a4e3c241.png)

**Comment by rnine** [comment]
Sad, sad, sad world.

**Comment by ryanfrancesconi** [comment]
truth. eh, probably shorter term can just change the NullAudio instructions to point to the apple project and say build and install yourself. I'd say that anyone wanting to work on Tests would be fine with that approach.

**Comment by ryanfrancesconi** [comment]
I updated the README just to point to the download. Seems fine for now. Updated 1 test for the current driver properties.
